---
- name: Gather facts about all Server Profiles
  oneview_server_profile_facts:
    config: "{{ config }}"
  delegate_to: localhost

- debug: msg = "{{server_profiles | map(attribute='name') | list }}"
- debug: var=server_profiles

- name: Gather paginated, filtered and sorted facts about Server Profiles
  oneview_server_profile_facts:
    config: "{{ config }}"
    params:
      start: 0
      count: 3
      sort: name:ascending
      filter: macType='Virtual'
  delegate_to: localhost

- debug: msg = "{{server_profiles | map(attribute='name') | list }}"

- name: Gather facts about a Server Profile by name
  oneview_server_profile_facts:
    config: "{{ config }}"
    name: "{{server_profile_name}}"
  delegate_to: localhost

- debug: var=server_profiles

- name: Gather facts about a Server Profile by uri
  oneview_server_profile_facts:
    config: "{{ config }}"
    uri: "{{server_profiles[0]['uri']}}"
  delegate_to: localhost

- debug: var=server_profiles

- name: Gather facts about available servers and bays for a given enclosure group and server hardware type
  oneview_server_profile_facts:
    config: "{{ config }}"
    options:
      - availableTargets:
          serverHardwareTypeUri: "{{server_hardware_type_uri}}"
          enclosureGroupUri: "{{enclosure_group_uri}}"
  delegate_to: localhost

- debug: var=server_profile_available_targets

- name: Gather all facts about a Server Profile
  oneview_server_profile_facts:
   config: "{{ config }}"
   name: "{{server_profile_name}}"
   options:
       - schema  # Supported only for API version <= 1200
       - compliancePreview
       - newProfileTemplate # Supported only for API version <= 1200
       - profilePorts:
          serverHardwareTypeUri: "{{server_hardware_type_uri}}"
          enclosureGroupUri: "{{enclosure_group_uri}}"
       - messages # Supported only for API version <= 500
       - transformation:
           serverHardwareTypeUri: "{{server_hardware_type_uri}}"
           enclosureGroupUri: "{{enclosure_group_uri}}"
       - availableNetworks:
           serverHardwareTypeUri: "{{server_hardware_type_uri}}"
           enclosureGroupUri: "{{enclosure_group_uri}}"
       - availableServers # Supported only for API version <= 1200
       - availableStorageSystem: # Supported only for API version <=500
           storageSystemId: "{{storage_system_id}}"
           serverHardwareTypeUri: "{{server_hardware_type_uri}}"
           enclosureGroupUri: "{{enclosure_group_uri}}"
       - availableStorageSystems: # Supported only for API version <=500
           serverHardwareTypeUri: "{{server_hardware_type_uri}}"
           enclosureGroupUri: "{{enclosure_group_uri}}"
       - availableTargets

  delegate_to: localhost

- debug: var=server_profiles
- debug: var=server_profile_schema
- debug: var=server_profile_compliance_preview
- debug: var=server_profile_new_profile_template
- debug: var=server_profile_profile_ports
- debug: var=server_profile_messages
- debug: var=server_profile_transformation
- debug: var=server_profile_available_networks
- debug: var=server_profile_available_servers
- debug: var=server_profile_available_storage_system
- debug: var=server_profile_available_storage_systems
- debug: var=server_profile_available_targets
