---
# defaults file for oneview_storage_pool_facts
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_storage_pool_facts/files/oneview_config.json"
- networks_query:
  - /rest/fc-networks/f61d2299-c6dd-4f81-bcd2-1f99dbae118a
- scope_uris: '/rest/scopes/754e0dce-3cbd-4188-8923-edf86f068bf7'
- scope_exclusions:
  - /rest/storage-pools/5F9CA89B-C632-4F09-BC55-A8AA00DA5C4A