---
galaxy_info:
  role_name: oneview_storage_system
  author: Chebrolu Bala Sai Harika
  description: Ansible role to manage OneView Storage resources.
  company: Hewlett Packard Enterprise
  license: Apache
  min_ansible_version: 2.9
  min_python_version: 3.4.2
  platforms: []
  galaxy_tags:
    - ansible
    - hpe-oneview
    - ansible-modules
    - sdk
dependencies: []
