---
- name: Get currentVersion from URL
  oneview_version_facts:
    config: "{{ config }}" 
  delegate_to: localhost
  when: contents.api_version == ""
  register: version

- name: Print currentVersion if api version is not specified in config file
  set_fact: 
    currentVersion: "{{ version.ansible_facts.version.currentVersion | int }}"
  when: contents.api_version == ""

- name: Print currentVersion if api version is specified in config file
  set_fact: 
    currentVersion: contents.api_version | string
  when: contents.api_version != ""

- name: Create a basic Hypervisor Cluster Profile
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: present
    data:
      type: "HypervisorClusterProfileV3"
      name: "{{ cluster_profile_name }}"
      hypervisorManagerUri: "{{ hyp_mgr }}"
      path: 'DC1'
      hypervisorType: 'Vmware'
      hypervisorHostProfileTemplate:
        serverProfileTemplateUri: "{{ spt_name }}"
        hostprefix: 'Test-cluster-host'
  delegate_to: localhost
  register: hyp_cp

# For creating virtual switch layout, enable that param and send the vswitch body under "hypervisorHostProfileTemplate:virtualSwitches"
- name: Create a Hypervisor Cluster Profile with vswitch
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: present
    params:
      create_vswitch_layout: True                          # If this is true, virtual switch layout will be created
    data:
      type: "HypervisorClusterProfileV3"
      description: "test cluster"
      hypervisorType: "Vmware"
      hypervisorClusterSettings:
        type: "Vmware"
        drsEnabled: True
        haEnabled: False
        multiNicVMotion: False
        virtualSwitchType: "Standard"
      hypervisorHostProfileTemplate:
        serverProfileTemplateUri: "{{ spt_name_ca }}"
        deploymentPlan:
          serverPassword: "test"
        hostprefix: "Test_cluster_profile_with_vswitch"
        virtualSwitches:                                 # this is the json body used to create vswitch
          serverProfileTemplateUri: "{{ spt_name_ca }}"
          hypervisorManagerUri: "{{ hyp_mgr }}"
        hostConfigPolicy:
          leaveHostInMaintenance: False
          useHostnameToRegister: False
        virtualSwitchConfigPolicy:
          manageVirtualSwitches: True
          configurePortGroups: True
      name: "{{ cluster_profile_name }}_with_vswitch"
      hypervisorManagerUri: "{{ hyp_mgr }}"
      path: "DC1"

  delegate_to: localhost
  register: hyp_cp_vswitch

- name: Do nothing with the Hypervisor Cluster Profile when no changes are provided
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ cluster_profile_name }}"
      hypervisorManagerUri: "{{ hyp_mgr }}"
      path: 'DC1'
      hypervisorType: 'Vmware'
  delegate_to: localhost

- name: Update the Hypervisor Cluster Profile changing the attribute name
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ cluster_profile_name }}"
      newName: "HCP-renamed"
      hypervisorManagerUri: "{{ hyp_mgr }}"
      path: 'DC1'
      hypervisorType: 'Vmware'
  delegate_to: localhost
  register: hyp_cp

- name: Delete the Hypervisor Cluster Profile
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: absent
    params:
      force: True
      soft_delete: False
    data: "{{ hyp_cp.ansible_facts.hypervisor_cluster_profile }}"
  delegate_to: localhost
  register: deleted

- name: Delete the Hypervisor Cluster Profile with vswitch
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: absent
    params:
      force: False
      soft_delete: False
    data: "{{ hyp_cp_vswitch.ansible_facts.hypervisor_cluster_profile }}"
  delegate_to: localhost
  register: deleted

- name: Do nothing when Hypervisor Cluster Profile is absent
  oneview_hypervisor_cluster_profile:
    config: "{{ config }}"
    state: absent
    data: "{{ hyp_cp.ansible_facts.hypervisor_cluster_profile }}"
  delegate_to: localhost
  register: deleted