---
- name: Gather facts about all ID Pools IPV4 Subnets
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
  delegate_to: localhost

- debug: var=id_pools_ipv4_subnets

- name: Gather paginated, and sorted facts about ID Pools IPV4 Subnets
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
    params:
      start: 0
      count: 3
      sort: 'name:descending'

- debug: var=id_pools_ipv4_subnets

- name: Gather facts about a ID pools by uri
  oneview_server_hardware_facts:
    config: "{{ config }}"
    uri: "{{ id_pools_ipv4_subnets[0]['uri'] }}"
  delegate_to: localhost

- name: Gather facts about ID Pools IPV4 Subnets by networkId
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
    networkId: "{{ id_pools_ipv4_subnets[0]['networkId'] }}"
  delegate_to: localhost

- name: Gather facts about a ID Pools IPV4 Subnet by name
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config_file_path }}"
    name: "{{ id_pools_ipv4_subnets[0]['name'] }}"
  delegate_to: localhost

- debug: var=id_pools_ipv4_subnets
