---  
- name: Ensure the ID Pools IPV4 Subnet exists
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ subnet_name }}'
      type: '{{ type }}'
      networkId: '{{ network_id }}'
      subnetmask: '{{ subnetmask }}'
      gateway: '{{ gateway }}'
      domain: '{{ domain }}'
      dnsServers: '{{ dnsServers }}'
  delegate_to: localhost

- name: Do nothing with the ID Pools IPV4 Subnet when no changes are provided
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      networkId: '{{ network_id }}'
      type: '{{ type }}'
  delegate_to: localhost

- name: Update the ID Pools IPV4 Subnet with awesome.com domain
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      networkId: '{{ network_id }}'
      domain: '{{ newDomain }}'
  delegate_to: localhost

- debug: var=id_pools_ipv4_subnet

- name: Create an Ethernet Network
  oneview_ethernet_network:
    config: "{{ config }}"
    state: present
    data:
      name: "SubnetNet"
      vlanId: "212"
      ethernetNetworkType: Tagged
      purpose: General
      smartLink: false
      privateNetwork: false
      subnetUri: '{{ id_pools_ipv4_subnet["uri"] }}'
      bandwidth:
          maximumBandwidth: 2000
          typicalBandwidth: 1000


- name: Create IPV4 Range 
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: "SubnetRange"
      subnetUri: '{{ id_pools_ipv4_subnet["uri"] }}'
      rangeCategory: Custom
      startStopFragments:
        - startAddress: "{{ start_address }}"
          endAddress: "{{ end_address }}"

- name: Allocate the no of IPv4 ID's
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: allocate
    data:
      networkId: '{{ network_id }}'
      count: '{{ count }}'
  delegate_to: localhost

- name: Get the allocated ID's List
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: collect
    data:
      networkId: '{{ network_id }}'
      idList: '{{ id_pools_ipv4_subnet["idList"] }}'
  delegate_to: localhost

- name: Delete the Ethernet Network
  oneview_ethernet_network:
    config: "{{ config }}"
    state: absent
    data:
      name: 'SubnetNet'

- name: Delete the ID Pools IPV4 Subnet
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: absent
    data:
      networkId: '{{ network_id }}'
  delegate_to: localhost

- name: Do nothing when ID Pools IPV4 Subnet is absent
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: absent
    data:
      networkId: '{{ network_id }}'
  delegate_to: localhost

- name: Create the ID Pools IPV4 Subnet for automation
  oneview_id_pools_ipv4_subnet:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ subnet_name }}'
      type: '{{ type }}'
      networkId: '{{ network_id }}'
      subnetmask: '{{ subnetmask }}'
      gateway: '{{ gateway }}'
      domain: '{{ domain }}'
      dnsServers: '{{ dnsServers }}'
  delegate_to: localhost
