---
- name: Gather facts about a Server Certificate by remote address
  oneview_certificates_server_facts:
    config: "{{ config }}"
    remote: "{{ remote_server }}"
  delegate_to: localhost

- set_fact:
    certificate: "{{ remote_certificate['certificateDetails'][0]['base64Data'] }}"

- name: Create a Repository
  oneview_repositories:
    config: "{{ config }}"
    state: present
    validate_etag: False
    data:
      name: "{{ repository_name }}"
      userName: 'Admin',
      password: '*******',
      repositoryURI: 'https://172.20.3.65/repositoryFolder',
      repositoryType: 'FirmwareExternalRepo',
      base64data: "{{ certificate }}"
  delegate_to: localhost
  register: repository

- name: Do nothing with the Repository when no changes are provided
  oneview_repositories:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ repository_name }}"
      userName: 'Admin',
      password: '*******',
      repositoryURI: 'https://172.20.3.65/repositoryFolder',
      repositoryType: 'FirmwareExternalRepo',
      base64data: "{{ certificate }}"
  delegate_to: localhost

- name: Update the repository changing the attribute name
  oneview_repositories:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ repository_name }}"
      newName: "{{ repository_name }}-updated"
  delegate_to: localhost

- name: Update the repository resource
  oneview_repositories:
    config: '{{ config }}'
    state: patch
    data:
      name: {{ repository_name }}"
  delegate_to: localhost

- name: Delete the Repository
  oneview_repositories:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ repository_name }}"
  delegate_to: localhost
  register: deleted

- name: Do nothing when Repository is absent
  oneview_repositories:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ repository_name }}"
  delegate_to: localhost
  register: deleted
