---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ config }}"
    name: "Test_Session"
  delegate_to: localhost
  register: session

- debug: var=session

#Server Certificate need to be added to appliance for using an Https web server
- name: Create a Server Certificate
  oneview_certificates_server:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    name: "{{ remote_server }}"
    data:
      certificateDetails:
        - aliasName: "{{ remote_server }}"
          base64Data: "{{ certificate }}"
  delegate_to: localhost

- name: Create a Repository
  oneview_repositories:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    validate_etag: False
    data:
      name: "{{ repository_name }}"
      userName: "{{ repository_username }}"
      password: "{{ repository_password }}"
      repositoryURI: "{{ repository_uri }}"
      repositoryType: "FirmwareExternalRepo"
  delegate_to: localhost
  register: repository

- name: Do nothing with the Repository when no changes are provided
  oneview_repositories:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    data:
      name: "{{ repository_name }}"
      userName: "{{ repository_username }}"
      password: "{{ repository_password }}"
      repositoryURI: "{{ repository_uri }}"
      repositoryType: "FirmwareExternalRepo"
  delegate_to: localhost

- name: Update the attributes of repository resource
  oneview_repositories:
    config: '{{ config }}'
    sessionID: "{{ session.ansible_facts.session }}"
    state: patch
    data:
      name: "{{ repository_name }}"
      newName: "{{ repository_name }}-updated"
  delegate_to: localhost

- name: Delete the Repository
  oneview_repositories:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: absent
    data:
      name: "{{ repository_name }}"
    params:
      force: True
  delegate_to: localhost
  register: deleted

- name: Do nothing when Repository is absent
  oneview_repositories:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: absent
    data:
      name: "{{ repository_name }}"
  delegate_to: localhost
  register: deleted
