---
- name: Gather facts about the Appliance Network Interfaces
  oneview_appliance_network_interface_facts:
    config: "{{ config }}"
  delegate_to: localhost

- debug: var=appliance_network_interfaces

- name: Gather facts about the Network Interfaces by Mac Address
  oneview_appliance_network_interface_facts:
    config: "{{ config }}"
    params:
       mac_address: "{{ mac_address }}"
  delegate_to: localhost

- name: Gather facts about the all unconfigured Mac Addresses
  oneview_appliance_network_interface_facts:
    config: "{{ config }}"
    params:
       get_all_mac_address: True
  delegate_to: localhost

- debug: var=appliance_network_interfaces