---
    #- name: Add a Server Hardware to create a Server Hardware Type (Prerequisite)
     # oneview_server_hardware:
     #   config: "{{ config }}"
     #   state: present
     #   data:
     #        hostname: '{{ server_hardware_hostname }}'
     #        username: '{{ server_hardware_username }}'
     #        password: '{{ server_hardware_password }}'
     #        force: false
     #        licensingIntent: "OneView"
     #        configurationState: "Managed"
     # delegate_to: localhost

    - name: Update the Server Hardware Type description
      oneview_server_hardware_type:
        config: "{{ config }}"
        state: present
        data:
          name: '{{ server_hardware_type_name }}'
          description: "New Description"
      delegate_to: localhost

    - name: Rename the Server Hardware Type
      oneview_server_hardware_type:
        config: "{{ config }}"
        state: present
        data:
            name: '{{ server_hardware_type_name }}'
            newName: '{{ server_hardware_type_name_renamed }}'
      delegate_to: localhost

    - name: Remove the Server Hardware to be able to delete the Server Hardware Type (Prerequisite)
      oneview_server_hardware:
        config: "{{ config }}"
        state: absent
        data:
          name: '{{ server_hardware_hostname }}'
      delegate_to: localhost

    - name: Delete the Server Hardware Type
      oneview_server_hardware_type:
        config: "{{ config }}"
        state: absent
        data:
          name: '{{ server_hardware_type_name_renamed }}'
      delegate_to: localhost
