---
- name: Gather facts about ID Pools IPV4 Subnets by networkId
  oneview_id_pools_ipv4_subnet_facts:
    config: "{{ config }}"
    networkId: '{{ networkId }}'
  delegate_to: localhost

- set_fact: subnet_uri="{{ id_pools_ipv4_subnets[0]['uri'] }}"

- name: Ensure the IPV4 Range '{{ range_name }}' exists
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ range_name }}'
      subnetUri: '{{ subnet_uri }}'
      rangeCategory: Custom
      startStopFragments:
        - startAddress: "{{ start_address }}"
          endAddress: "{{ end_address1 }}"
  delegate_to: localhost

- set_fact: uri="{{ id_pools_ipv4_range['uri'] }}"

- name: Update the ID Pools IPV4 Range with end address 101
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ range_name }}'
      uri: '{{ uri }}'
      startStopFragments:
        - startAddress: "{{ start_address }}"
          endAddress: "{{ end_address2 }}"
  delegate_to: localhost

- name: Ensure the IPV4 Range is enabled
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ range_name }}'
      subnetUri: '{{ subnet_uri }}'
      enabled: True
  delegate_to: localhost

- name: Create an Enclosure Group
  oneview_enclosure_group:
    config: "{{ config }}"
    state: present
    data:
      name: "EGRange"
      ipAddressingMode: "ipPool"
      enclosureCount: 3
      ipRangeUris:
        - '{{ id_pools_ipv4_range["uri"]}}'


- name: Allocates ID from an IPV4 Range
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      uri: "{{ uri }}"
      count: 2
      update_allocator: True
      idList: '{{ idList }}'
  delegate_to: localhost

- name: Collects set of ID from an IPV4 Range
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      uri: "{{ uri }}"
      update_collector: True
      idList: '{{ id_pools_ipv4_range["idList"] }}'
  delegate_to: localhost

- name: Delete the Enclosure Group
  oneview_enclosure_group:
    config: "{{ config }}"
    state: absent
    data:
      name: "EGRange"
  delegate_to: localhost

- name: Ensure the IPV4 Range is disabled with DISABLED tag in the name
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ range_name }}'
      newName: '{{ disabled_range_name }}'
      subnetUri: '{{ subnet_uri }}'
      enabled: True
  delegate_to: localhost

- name: Delete the ID Pools IPV4 Range
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: absent
    data:
      name: '{{ disabled_range_name }}'
      subnetUri: '{{ subnet_uri }}'
  delegate_to: localhost

- name: Do nothing when ID Pools IPV4 Range is absent
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: absent
    data:
      name: '{{ disabled_range_name }}'
      subnetUri: '{{ subnet_uri }}'
  delegate_to: localhost

- name: Create the IPV4 Range '{{ range_name }}' for automation
  oneview_id_pools_ipv4_range:
    config: "{{ config }}"
    state: present
    data:
      name: '{{ range_name }}'
      subnetUri: '{{ subnet_uri }}'
      rangeCategory: Custom
      startStopFragments:
        - startAddress: "{{ start_address }}"
          endAddress: "{{ end_address1 }}"
  delegate_to: localhost 
