---
# This operation is only available on HPE Synergy
- name: Create a Logical Enclosure (available only on HPE Synergy)
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: present
    data:
        enclosureUris: "{{ enclosure_uri }}"
        enclosureGroupUri: "{{ enclosure_group_uri }}"
        name: "{{ logical_enclosure_name }}"
  ignore_errors: true
  delegate_to: localhost
  when: variant == "Synergy"

- name: Update the firmware for the Logical Enclosure
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: firmware_updated
    data:
        name: "{{ logical_enclosure_name }}"
        firmware:
            firmwareBaselineUri: "{{ firmware_baseline_uri }}"
            firmwareUpdateOn: "EnclosureOnly"
            forceInstallFirmware: "false"
        custom_headers:
            if-Match: '*'
  ignore_errors: true
  delegate_to: localhost

# This play is compatible with Synergy Enclosures
- name: Update the firmware for the Logical Enclosure with the logical-interconnect validation set as true
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: firmware_updated
    data:
        name: "{{ logical_enclosure_name }}"
        firmware:
            firmwareBaselineUri: "{{ firmware_baseline_uri }}"
            firmwareUpdateOn: "EnclosureOnly"
            forceInstallFirmware: "false"
            validateIfLIFirmwareUpdateIsNonDisruptive: "true"
            logicalInterconnectUpdateMode: "Orchestrated"
            updateFirmwareOnUnmanagedInterconnect: "true"
        custom_headers:
            if-Match: '*'
  ignore_errors: true
  delegate_to: localhost
  when: variant == "Synergy"

- name: Update the Logical Enclosure configuration script(available only on C7000)
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: script_updated
    data:
        name: "{{ logical_enclosure_name }}"
        configurationScript: "# script (updated)"
  ignore_errors: true
  delegate_to: localhost
  when: variant == "C7000"

- name: Generates a support dump for the Logical Enclosure
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: dumped
    data:
        name: "{{ logical_enclosure_name }}"
        dump:
          errorCode: "MyDump16"
          encrypt: "true"
          excludeApplianceDump: "false"
  delegate_to: localhost
- debug: var=generated_dump_uri

- name: Reconfigure all enclosures associated with logical enclosure
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: reconfigured
    data:
        name: "{{ logical_enclosure_name }}"
  delegate_to: localhost

- name: Makes the logical enclosure consistent with the enclosure group
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: updated_from_group
    data:
        name: "{{ logical_enclosure_name }}"
  delegate_to: localhost

- name: Update the Logical Enclosure changing the name attribute
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ logical_enclosure_name }}"
        newName: "{{ logical_enclosure_name }} (renamed)"
  delegate_to: localhost

- name: Rename the Logical Enclosure to its initial name
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ logical_enclosure_name }} (renamed)"
        newName: "{{ logical_enclosure_name }}"
  delegate_to: localhost

# This state is only available on HPE Synergy
- name: Delete a Logical Enclosure (available only on HPE Synergy)
  oneview_logical_enclosure:
    config: "{{ config }}"
    state: absent
    data: '{{ logical_enclosure }}'
  ignore_errors: true
  delegate_to: localhost
  when: variant == "Synergy"
