---
# defaults file for oneview_id_pools_ipv4_ranges
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_id_pools_ipv4_range/files/oneview_config.json"
subnet_name: IPv4Subnet
range_name: Experts Range
disabled_range_name: DISABLED - Experts Range
networkId: "192.168.20.0"
start_address: "192.168.20.10"
end_address1: "192.168.20.30"
end_address2: "192.168.20.50"
