---
# defaults file for oneview_id_pools_ipv4_ranges
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_id_pools_ipv4_range/files/oneview_config.json"
subnet_name: IPv4Subnet
range_name: Experts Range
disabled_range_name: DISABLED - Experts Range
networkId: "<network_id>"
start_address: "<start_address>"
end_address1: "<end_address>"
end_address2: "<end_address2>"
idList: ["<ip_address1>", "<ip_address2>"]
