---
# defaults file for oneview_server_profile
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_fc_network/files/oneview_config.json"
# Set the name of the server profile template that will be used to provision the server profile
ov_template:  ProfileTemplate101
# Set the name of an existing enclosure group to run this example
enclosure_group_name: SYN03_EC
# Set the name of an existing server hardware type to run this example
server_hardware_type_name: SY 480 Gen9 4
# Set the name of an existing ethernet network
network_name: eth77
