---
# defaults file for oneview_sas_interconnect_type_facts
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_sas_interconnect_type_facts/files/oneview_config.json"
config_file: "{{lookup('file', config)}}"
contents: "{{lookup('file','../config/config.json') | from_json}}"
