---
- name: Create an Enclosure Group
  oneview_enclosure_group:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ enclosure_group_name }}"
        ipAddressingMode: "External"
        interconnectBayMappings:
            - interconnectBay: 1
            - interconnectBay: 2
            - interconnectBay: 3
            - interconnectBay: 4
            - interconnectBay: 5
            - interconnectBay: 6
  delegate_to: localhost

- name: Do nothing with the Enclosure Group when no changes are provided
  oneview_enclosure_group:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ enclosure_group_name }}"
        stackingMode: "Enclosure" # Not supported in V600
        interconnectBayMappings:
            - interconnectBay: 1
            - interconnectBay: 2
            - interconnectBay: 3
            - interconnectBay: 4
            - interconnectBay: 5
            - interconnectBay: 6
  delegate_to: localhost

- name: Update the Enclosure Group changing the name attribute
  oneview_enclosure_group:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ enclosure_group_name }}"
        newName: "{{ enclosure_group_new_name }}"
  delegate_to: localhost

- name: Delete the Enclosure Group
  oneview_enclosure_group:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ enclosure_group_new_name }}"
  delegate_to: localhost

# This play is compatible with C7000 Enclosures
- name: Update the Enclosure Group configuration script
  oneview_enclosure_group:
    config: "{{ config }}"
    state: present
    data:
        name: "{{ enclosure_group_new_name }}"
        configurationScript: "# script (updated)"
  delegate_to: localhost
  when: variant == "C7000"

- name: Do nothing when Enclosure Group is absent
  oneview_enclosure_group:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ enclosure_group_new_name }}"
  delegate_to: localhost
