---
# Below task creates a Logical Interconnect Group with Interconnects, upLinkPorts, uplinkSets containing EthernetNetworks
- name: Create a Logical Interconnect Group
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ lig_name }}"
      enclosureType: 'SY12000'
      uplinkSets:
        - name: 'e23 uplink set'
          mode: 'Auto'
          networkType: 'Ethernet'
          ethernetNetworkType: 'Tagged'
          networkNames:
            - "{{ network_name_1 }}"
            - "{{ network_name_2 }}"
          networkUris:
            - "{{ network_uri_1 }}"
          logicalPortConfigInfos:
           - desiredSpeed: 'Auto'
             logicalLocation:
                  locationEntries:
                    - relativeValue: 1
                      type: 'Enclosure'
                    - relativeValue: 61
                      type: 'Port'
                    - relativeValue: 3
                      type: 'Bay'
        - name: 'e23 uplink set1'
          mode: 'Auto'
          networkType: 'Ethernet'
          ethernetNetworkType: 'Untagged'
          networkUris:
            - "{{ network_uri_2 }}"
          logicalPortConfigInfos:
           - desiredSpeed: 'Auto'
             logicalLocation:
                  locationEntries:
                    - relativeValue: 2
                      type: 'Enclosure'
                    - relativeValue: 62
                      type: 'Port'
                    - relativeValue: 6
                      type: 'Bay'
      interconnectBaySet: 3
      enclosureIndexes: [1,2,3]
      redundancyType: "HighlyAvailable"
      interconnectMapTemplate:
        interconnectMapEntryTemplates:
          - enclosureIndex: 3
            logicalLocation:
                locationEntries:
                    - relativeValue: 3
                      type: "Enclosure"
                    - relativeValue: 6
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_2 }}"
          - enclosureIndex: 2
            logicalLocation:
                locationEntries:
                    - relativeValue: 2
                      type: "Enclosure"
                    - relativeValue: 6
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_1 }}"
          - enclosureIndex: 2
            logicalLocation:
                locationEntries:
                    - relativeValue: 2
                      type: "Enclosure"
                    - relativeValue: 3
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_2 }}"
          - enclosureIndex: 3
            logicalLocation:
                locationEntries:
                    - relativeValue: 3
                      type: "Enclosure"
                    - relativeValue: 3
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_2 }}"
          - enclosureIndex: 1
            logicalLocation:
                locationEntries:
                    - relativeValue: 1
                      type: "Enclosure"
                    - relativeValue: 6
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_2 }}"
          - enclosureIndex: 1
            logicalLocation:
                locationEntries:
                    - relativeValue: 1
                      type: "Enclosure"
                    - relativeValue: 3
                      type: "Bay"
            permittedInterconnectTypeName: "{{ permitted_interconnect_type_name_1 }}"
           # Alternatively you can inform permittedInterconnectTypeUri
  delegate_to: localhost

- name: Do nothing with the Logical Interconnect Group when no changes are provided
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ lig_name }}"
      enclosureType: 'SY12000'
  delegate_to: localhost

- name: Update the Logical Interconnect Group by adding an uplink set "e23 uplink set2" with an Ethernet network
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ lig_name }}"
      enclosureType: 'SY12000'
      uplinkSets:
        - name: 'e23 uplink set2'
          mode: 'Auto'
          networkType: 'Ethernet'
          networkUris:
            - "{{ network_uri_3 }}"
          logicalPortConfigInfos:
            - desiredSpeed: 'Auto'
              logicalLocation:
                  locationEntries:
                    - relativeValue: 3
                      type: "Bay"
                    - relativeValue: 62
                      type: "Port"
                    - relativeValue: 1
                      type: "Enclosure"
  delegate_to: localhost

# Below task is supported only with OneView 3.10
- name: Update the Logical Interconnect Group with two scopes
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ lig_name }}"
      scopeUris: "{{ scope_uris }}"
  delegate_to: localhost

- name: Rename the Logical Interconnect Group to 'Updated Logical Interconnect Group'
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: present
    data:
      name: "{{ lig_name }}"
      newName: "{{ lig_new_name }}"
  delegate_to: localhost

- name: Delete the Logical Interconnect Group
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ lig_new_name }}"
  delegate_to: localhost
  register: deleted

- name: Do nothing when the Logical Interconnect Group is absent
  oneview_logical_interconnect_group:
    config: "{{ config }}"
    state: absent
    data:
      name: "{{ lig_new_name }}"
  delegate_to: localhost
  register: deleted
