---
- name: Fetch Session Id
  oneview_get_session_id:
    config: "{{ config }}"
    name: "Test_Session"
  delegate_to: localhost
  register: session

- debug: var=session

- name: Upload the firmware bundle
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    file_path: "{{ spp_bundle_path }}"
  delegate_to: localhost

- name: Ensure the firmware bundle is present
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    file_path: "{{ spp_bundle_path }}"
  delegate_to: localhost

- name: Upload the hotfix
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    file_path: "{{ hotfix_path }}"
  delegate_to: localhost

- name: Ensure the hotfix is present
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: present
    file_path: "{{ hotfix_path }}"
  delegate_to: localhost

- name: Upload the compsig file
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: add_signature
    file_path: "{{ compsig_file }}"
  delegate_to: localhost

- name: Ensure the compsig file is already present
  oneview_firmware_bundle:
    config: "{{ config }}"
    sessionID: "{{ session.ansible_facts.session }}"
    state: add_signature
    file_path: "{{ compsig_file }}"
  delegate_to: localhost
