---
# defaults file for oneview_id_pools_ipv4_subnets
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_id_pools_ipv4_subnets/files/oneview_config.json"
subnet_name: Test IPv4 Subnet
networkId: '10.1.0.0'
