---
# defaults file for oneview_id_pools_ipv4_subnets
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_id_pools_ipv4_subnet/files/oneview_config.json"
subnet_name: Test IPv4 Subnet
network_id: "192.168.20.0"
type: Subnet
subnetmask: "255.255.255.0"
gateway: "192.168.20.1"
domain: example.com
dnsServers: ["192.170.20.20"]
count: 3
newDomain: awesome.com
start_address: "192.168.20.10"
end_address: "192.168.20.20"
