---
- hosts: all
  collections:
    - hpe.oneview
  roles:
    # - hpe.oneview.oneview_ethernet_network
    - hpe.oneview.oneview_appliance_device_snmp_v3_trap_destination
    # - hpe.oneview.oneview_appliance_device_snmp_v3_users