---
# defaults file for oneview_logical_interconnect
config: "~/.ansible/collections/ansible_collections/hpe/oneview/roles/oneview_logical_interconnect/files/oneview_config.json"
contents: "{{lookup('file', config)}}"
logical_interconnect_name: "SYN03_LE-SYN03_LIG" # Set the name of a Logical interconnect to run the playbook
network_name: "eth77" # Set the name of an existent Ethernet Network to update the internal networks
firmware_driver: "HPE Synergy Custom SPP 2018110 2019 02 15, 2019.02.15.00" # Set the SPP filename to install it
scope_uris: # List of scope URIs to be used in the 'scopes_updated' state
  - "/rest/scopes/74877630-9a22-4061-9db4-d12b6c4cfee0"
variant: "Synergy"