name: Upload release to Galaxy

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Setup environment for collection publish
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Build and publish
      run: |
        ansible-galaxy collection build .
        ansible-galaxy collection publish hpe-oneview-${{ env.RELEASE_VERSION }}.tar.gz --api-key="${{ secrets.GALAXY_API_TOKEN }}"
